language: cpp
compiler:
- gcc
install:
# Upgrade GCC
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

# Download conan
- wget http://downloads.conan.io/latest_debian -O conan.deb
- sudo dpkg -i conan.deb
- rm conan.deb

# Automatic detection of your arch, compiler, etc
- conan install

script:
- mkdir build
- cd build && cmake ../ -DBUILD_TEST=TRUE && cmake --build .
- cat ../conanbuildinfo.cmake
- ./bin/encryption_test