language: cpp
compiler:
- gcc
install:
# Upgrade GCC
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9


############################################################################
# All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
############################################################################
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

############################################################################
# Install a recent CMake
############################################################################
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  else
    brew install cmake
  fi
  cd ..



# Download conan
- wget http://downloads.conan.io/latest_debian -O conan.deb
- sudo dpkg -i conan.deb
- rm conan.deb

# Automatic detection of your arch, compiler, etc
- conan install

before_script:
 # - ls
 # - find . -name "protoc"
 - chmod a+x protoc
 - ls -ltra > fer.txt
 - cat fer.txt
 # - getfacl .
 # - ls -lead
 - ls -ld .
 # - ./protoc --version
 - ./protoc message.proto --cpp_out="."

script:
 - mkdir build
 - cd build && cmake ../ -DBUILD_TEST=TRUE && cmake --build .
 #- cat ../conanbuildinfo.cmake
 - ./bin/encryption_test